package com.teacup.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.teacup.db.SqBean;

import com.teacup.db.SqBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sqBeanDaoConfig;

    private final SqBeanDao sqBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sqBeanDaoConfig = daoConfigMap.get(SqBeanDao.class).clone();
        sqBeanDaoConfig.initIdentityScope(type);

        sqBeanDao = new SqBeanDao(sqBeanDaoConfig, this);

        registerDao(SqBean.class, sqBeanDao);
    }
    
    public void clear() {
        sqBeanDaoConfig.clearIdentityScope();
    }

    public SqBeanDao getSqBeanDao() {
        return sqBeanDao;
    }

}
